# -*- coding: utf-8 -*-
"""Guardy_Hybrid_ML_Training_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x1-sxiXqHv4e4JJ26l_Gb3U9VruFMekB

# Guardy Hybrid ML Training Colab

This notebook trains a Guardy phishing URL model using a dataset mix designed for the project:

- phishing URLs from PhishTank
- phishing URLs from OpenPhish Community Feed, when available
- malicious/phishing-tagged URLs from URLhaus
- legitimate domains from Tranco, Majestic Million, and Cisco Umbrella
- official safe brand URLs generated from Guardy's `brands.json`
- synthetic brand-impersonation phishing URLs generated from Guardy's `brands.json`
- optional uploaded datasets such as PhiUSIIL or LegitPhish

## 1. Environment Setup
"""

!pip -q install pandas==2.2.2 scikit-learn==1.6.1 xgboost==2.1.3 joblib tldextract matplotlib seaborn requests

import json
import copy
import math
import os
import pickle
import random
import re
import time
import zipfile
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

import joblib
import numpy as np
import pandas as pd
import requests
import tldextract
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_validate
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
    precision_recall_curve,
)
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from xgboost import XGBClassifier

RANDOM_SEED = 42
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

CONTENT_DIR = Path("/content")
DATA_DIR = CONTENT_DIR / "guardy_hybrid_data"
EXPORT_DIR = CONTENT_DIR / "guardy_hybrid_exports"
DATA_DIR.mkdir(parents=True, exist_ok=True)
EXPORT_DIR.mkdir(parents=True, exist_ok=True)

pd.set_option("display.max_colwidth", 180)
print("Environment ready.")

"""## 2. Training Configuration"""

BACKEND_COMPATIBLE_39 = True

MAX_PHISHTANK = 1_000_000
MAX_OPENPHISH = 100_000
MAX_URLHAUS = 300_000
MAX_TOP_DOMAIN_LEGIT = 500_000
MAX_OPTIONAL_DATASET_ROWS = 300_000
MAX_TOTAL_TRAINING_ROWS = 1_000_000
TARGET_PHISHING_RATIO = 0.40

# Official brand calibration and synthetic brand-abuse weights.
OFFICIAL_CALIBRATION_REPEAT_FACTOR = 25
PAYPAL_OFFICIAL_ACCOUNT_REPEAT_FACTOR = 300
SYNTHETIC_PHISH_REPEAT_FACTOR = 8

# Lighter CV is intentional at large row counts to avoid memory duplication in Colab.
CV_SPLITS = 2
CV_N_JOBS = 1

print("Backend-compatible 39-feature mode:", BACKEND_COMPATIBLE_39)
print("MAX_PHISHTANK:", MAX_PHISHTANK)
print("MAX_OPENPHISH:", MAX_OPENPHISH)
print("MAX_URLHAUS:", MAX_URLHAUS)
print("MAX_TOP_DOMAIN_LEGIT:", MAX_TOP_DOMAIN_LEGIT)
print("MAX_OPTIONAL_DATASET_ROWS:", MAX_OPTIONAL_DATASET_ROWS)
print("MAX_TOTAL_TRAINING_ROWS:", MAX_TOTAL_TRAINING_ROWS)
print("TARGET_PHISHING_RATIO:", TARGET_PHISHING_RATIO)
print("OFFICIAL_CALIBRATION_REPEAT_FACTOR:", OFFICIAL_CALIBRATION_REPEAT_FACTOR)
print("PAYPAL_OFFICIAL_ACCOUNT_REPEAT_FACTOR:", PAYPAL_OFFICIAL_ACCOUNT_REPEAT_FACTOR)
print("SYNTHETIC_PHISH_REPEAT_FACTOR:", SYNTHETIC_PHISH_REPEAT_FACTOR)
print("CV_SPLITS:", CV_SPLITS)
print("CV_N_JOBS:", CV_N_JOBS)

"""## 3. Upload Guardy Brand Registry


"""

from google.colab import files

print("Upload brands.json now.")
uploaded_brand_files = files.upload()

brands_json_path = None
for name, content in uploaded_brand_files.items():
    if name.lower().endswith(".json"):
        path = DATA_DIR / name
        path.write_bytes(content)
        brands_json_path = path
        break

if brands_json_path is None:
    raise FileNotFoundError("brands.json is required for Guardy-specific training.")

guardy_brands = json.loads(brands_json_path.read_text(encoding="utf-8"))
print("Loaded brand profiles:", len(guardy_brands))
display(pd.DataFrame(guardy_brands).head())

def registered_domain(hostname_or_domain):
    value = str(hostname_or_domain or "").lower().strip().strip(".")
    if "://" in value:
        value = urlparse(value).hostname or value
    ext = tldextract.extract(value)
    if ext.domain and ext.suffix:
        return f"{ext.domain}.{ext.suffix}".lower()
    return value


brand_keywords = sorted({
    str(keyword).lower().strip()
    for brand in guardy_brands
    for keyword in brand.get("keywords", [])
    if str(keyword).strip()
})

official_exact_domains = sorted({
    str(domain).lower().strip()
    for brand in guardy_brands
    for domain in brand.get("official_domains", [])
    if str(domain).strip()
})

official_registered_domains = sorted({registered_domain(domain) for domain in official_exact_domains})
official_domain_set = sorted(set(official_exact_domains) | set(official_registered_domains))

print("Brand keywords:", len(brand_keywords))
print("Official/extracted domains:", len(official_domain_set))
display(pd.DataFrame({"official_domain": official_domain_set}).head(20))

"""## 4. Download Phishing And Legitimate Sources

Sources:

- PhishTank verified online phishing URLs
- Tranco top domains
- Majestic Million domains
- Cisco Umbrella top domains

"""

def download_text(url, output_path, headers=None, timeout=90):
    output_path = Path(output_path)
    try:
        response = requests.get(url, headers=headers or {}, timeout=timeout)
        response.raise_for_status()
        output_path.write_bytes(response.content)
        print("Downloaded:", url, "->", output_path, f"({len(response.content):,} bytes)")
        return output_path
    except Exception as exc:
        print("Download failed:", url)
        print("Reason:", exc)
        return None


def read_zip_first_csv(zip_path):
    with zipfile.ZipFile(zip_path, "r") as zf:
        csv_names = [name for name in zf.namelist() if name.lower().endswith(".csv")]
        if not csv_names:
            raise ValueError(f"No CSV in {zip_path}")
        with zf.open(csv_names[0]) as f:
            return pd.read_csv(f, header=None)


phishtank_csv = download_text(
    "https://data.phishtank.com/data/online-valid.csv",
    DATA_DIR / "phishtank_online_valid.csv",
    headers={"User-Agent": "GuardyResearch/1.0 educational phishing detection model training"},
)

openphish_txt = download_text(
    "https://openphish.com/feed.txt",
    DATA_DIR / "openphish_feed.txt",
    headers={"User-Agent": "GuardyResearch/1.0 educational phishing detection model training"},
)

urlhaus_csv = download_text(
    "https://urlhaus.abuse.ch/downloads/csv/",
    DATA_DIR / "urlhaus_urls.csv",
    headers={"User-Agent": "GuardyResearch/1.0 educational phishing detection model training"},
)

tranco_zip = download_text(
    "https://tranco-list.eu/top-1m.csv.zip",
    DATA_DIR / "tranco_top_1m.csv.zip",
)

majestic_csv = download_text(
    "https://downloads.majestic.com/majestic_million.csv",
    DATA_DIR / "majestic_million.csv",
)

umbrella_zip = download_text(
    "https://s3-us-west-1.amazonaws.com/umbrella-static/top-1m.csv.zip",
    DATA_DIR / "umbrella_top_1m.csv.zip",
)

"""## 5. Build Dataset

Final schema:

- `url`
- `label`, where `0 = legitimate`, `1 = phishing`
- `source`

"""

def normalize_url(value):
    value = str(value or "").strip()
    if not value or value.lower() == "nan":
        return None
    if "://" not in value:
        value = "https://" + value
    return value


def make_df(urls, label, source):
    cleaned = []
    for url in urls:
        norm = normalize_url(url)
        if norm:
            cleaned.append(norm)
    return pd.DataFrame({"url": cleaned, "label": int(label), "source": source})


frames = []

# PhishTank.
if phishtank_csv and phishtank_csv.exists():
    try:
        pt = pd.read_csv(phishtank_csv)
        url_col = "url" if "url" in pt.columns else None
        if url_col:
            pt_urls = pt[url_col].dropna().astype(str).tolist()
            random.Random(RANDOM_SEED).shuffle(pt_urls)
            frames.append(make_df(pt_urls[:MAX_PHISHTANK], 1, "phishtank"))
            print("PhishTank phishing rows:", len(frames[-1]))
    except Exception as exc:
        print("Could not parse PhishTank:", exc)

# OpenPhish Community Feed.
if openphish_txt and openphish_txt.exists():
    try:
        op_urls = [line.strip() for line in openphish_txt.read_text(encoding="utf-8", errors="ignore").splitlines()]
        op_urls = [url for url in op_urls if url.startswith(("http://", "https://"))]
        random.Random(RANDOM_SEED).shuffle(op_urls)
        frames.append(make_df(op_urls[:MAX_OPENPHISH], 1, "openphish"))
        print("OpenPhish phishing rows:", len(frames[-1]))
    except Exception as exc:
        print("Could not parse OpenPhish:", exc)

# URLhaus. Prefer phishing-tagged URLs when tags exist; otherwise use all URLs as malicious.
def read_urlhaus_csv(path):
    path = Path(path)
    read_kwargs = dict(comment="#", header=None, low_memory=False, on_bad_lines="skip")

    # URLhaus may be served as ZIP/gzip bytes depending on endpoint/proxy behavior.
    if zipfile.is_zipfile(path):
        with zipfile.ZipFile(path, "r") as zf:
            csv_names = [name for name in zf.namelist() if name.lower().endswith((".csv", ".txt"))]
            if not csv_names:
                raise ValueError("URLhaus archive did not contain CSV/TXT")
            with zf.open(csv_names[0]) as f:
                return pd.read_csv(f, encoding="latin-1", **read_kwargs)

    for encoding in ["utf-8", "latin-1", "cp1252"]:
        try:
            return pd.read_csv(path, encoding=encoding, **read_kwargs)
        except UnicodeDecodeError:
            continue
    return pd.read_csv(path, encoding="latin-1", **read_kwargs)


if urlhaus_csv and urlhaus_csv.exists():
    try:
        uh = read_urlhaus_csv(urlhaus_csv)
        # Common URLhaus CSV columns include id,dateadded,url,url_status,last_online,threat,tags,urlhaus_link,reporter.
        if uh.shape[1] >= 3:
            url_col = 2
            tags_col = 6 if uh.shape[1] > 6 else None
            if tags_col is not None:
                tags = uh[tags_col].astype(str).str.lower()
                phishing_mask = tags.str.contains("phish", na=False)
                uh_filtered = uh[phishing_mask]
                if len(uh_filtered) < 1_000:
                    print("URLhaus phishing-tagged rows were low; using all URLhaus malicious URLs instead.")
                    uh_filtered = uh
            else:
                uh_filtered = uh
            uh_urls = uh_filtered[url_col].dropna().astype(str).tolist()
            uh_urls = [url for url in uh_urls if url.startswith(("http://", "https://"))]
            random.Random(RANDOM_SEED).shuffle(uh_urls)
            frames.append(make_df(uh_urls[:MAX_URLHAUS], 1, "urlhaus_malicious"))
            print("URLhaus malicious rows:", len(frames[-1]))
        else:
            print("URLhaus CSV had unexpected column count:", uh.shape[1])
    except Exception as exc:
        print("Could not parse URLhaus:", exc)


def top_domains_from_tranco_zip(path, limit):
    if not path or not Path(path).exists():
        return []
    df = read_zip_first_csv(path)
    if df.shape[1] >= 2:
        return df.iloc[:, 1].dropna().astype(str).head(limit).tolist()
    return []


def top_domains_from_umbrella_zip(path, limit):
    if not path or not Path(path).exists():
        return []
    df = read_zip_first_csv(path)
    if df.shape[1] >= 2:
        return df.iloc[:, 1].dropna().astype(str).head(limit).tolist()
    return []


def top_domains_from_majestic_csv(path, limit):
    if not path or not Path(path).exists():
        return []
    df = pd.read_csv(path)
    domain_col = "Domain" if "Domain" in df.columns else None
    if domain_col:
        return df[domain_col].dropna().astype(str).head(limit).tolist()
    return []


legit_domains = []
per_source_limit = MAX_TOP_DOMAIN_LEGIT // 3
tranco_domains = top_domains_from_tranco_zip(tranco_zip, per_source_limit)
majestic_domains = top_domains_from_majestic_csv(majestic_csv, per_source_limit)
umbrella_domains = top_domains_from_umbrella_zip(umbrella_zip, per_source_limit)

print("Tranco domains:", len(tranco_domains))
print("Majestic domains:", len(majestic_domains))
print("Umbrella domains:", len(umbrella_domains))

for domains, source in [
    (tranco_domains, "tranco"),
    (majestic_domains, "majestic"),
    (umbrella_domains, "umbrella"),
]:
    if domains:
        frames.append(make_df([f"https://{d}" for d in domains], 0, source))
        print(source, "legitimate rows:", len(frames[-1]))

SAFE_PATHS = [
    "",
    "/login",
    "/signin",
    "/sign-in",
    "/account",
    "/security",
    "/support",
    "/help",
    "/privacy",
    "/tracking",
    "/myaccount",
    "/myaccount/summary",
    "/myaccount/security",
    "/myaccount/settings",
    "/myaccount/money",
    "/myaccount/wallet",
    "/us/signin",
    "/lt/signin",
    "/business/signin",
    "/webapps/mpp/account-selection",
    "/webapps/mpp/security/security-protections",
    "/us/security/report-suspicious-messages",
]

official_safe_urls = []
for domain in official_registered_domains:
    for prefix in ["https://", "https://www."]:
        for path in SAFE_PATHS:
            official_safe_urls.append(prefix + domain + path)

official_safe_df = make_df(official_safe_urls, 0, "guardy_official_domains")
official_safe_weighted_df = pd.concat(
    [official_safe_df] * OFFICIAL_CALIBRATION_REPEAT_FACTOR,
    ignore_index=True,
)
frames.append(official_safe_weighted_df)

paypal_official_account_urls = [
    "https://www.paypal.com/signin",
    "https://www.paypal.com/us/signin",
    "https://www.paypal.com/lt/signin",
    "https://www.paypal.com/myaccount",
    "https://www.paypal.com/myaccount/summary",
    "https://www.paypal.com/myaccount/security",
    "https://www.paypal.com/myaccount/settings",
    "https://www.paypal.com/myaccount/money",
    "https://www.paypal.com/myaccount/wallet",
    "https://www.paypal.com/business/signin",
    "https://www.paypal.com/webapps/mpp/account-selection",
    "https://www.paypal.com/webapps/mpp/security/security-protections",
    "https://www.paypal.com/us/security/report-suspicious-messages",
]
paypal_account_df = make_df(paypal_official_account_urls, 0, "guardy_paypal_official_account_calibration")
paypal_account_weighted_df = pd.concat(
    [paypal_account_df] * PAYPAL_OFFICIAL_ACCOUNT_REPEAT_FACTOR,
    ignore_index=True,
)
frames.append(paypal_account_weighted_df)

print("Official safe unique URLs:", len(official_safe_df))
print("Official safe weighted rows:", len(official_safe_weighted_df))
print("PayPal targeted official account rows:", len(paypal_account_weighted_df))


PHISHING_TLDS = ["xyz", "top", "cfd", "click", "icu", "cyou", "site", "online", "support", "shop"]
PHISHING_WORDS = ["login", "secure", "verify", "account", "update", "wallet", "tracking", "security"]

synthetic_phish_urls = []
for brand in guardy_brands:
    keywords = [str(k).lower().replace(" ", "").replace("_", "-") for k in brand.get("keywords", [])]
    keywords = [k for k in keywords if k and len(k) > 1]
    for keyword in keywords[:3]:
        for word in PHISHING_WORDS:
            for tld in PHISHING_TLDS[:5]:
                synthetic_phish_urls.append(f"http://{keyword}-{word}.{tld}/verify?account=1")
                synthetic_phish_urls.append(f"http://{keyword}-{word}-secure.{tld}/login")
        official_domains = [registered_domain(d) for d in brand.get("official_domains", [])]
        for official in official_domains[:2]:
            synthetic_phish_urls.append(f"http://{official}.login-secure-update.xyz/account")
            synthetic_phish_urls.append(f"http://secure-{keyword}.{official}.verify-user.top/login")

synthetic_phish_df = make_df(synthetic_phish_urls, 1, "synthetic_brand_impersonation")
synthetic_phish_df = synthetic_phish_df.drop_duplicates(subset=["url"])
synthetic_phish_weighted_df = pd.concat(
    [synthetic_phish_df] * SYNTHETIC_PHISH_REPEAT_FACTOR,
    ignore_index=True,
)
frames.append(synthetic_phish_weighted_df)
print("Synthetic phishing unique URLs:", len(synthetic_phish_df))
print("Synthetic phishing weighted rows:", len(synthetic_phish_weighted_df))

"""## 6. Optional Uploaded Datasets

Optional uploads:

- PhiUSIIL CSV
- LegitPhish CSV
- any CSV with URL and label columns

"""

print("Optional: upload PhiUSIIL / LegitPhish / custom URL-label CSV files, or cancel to skip.")
try:
    optional_uploads = files.upload()
except Exception:
    optional_uploads = {}


def normalize_external_dataset(raw_df, source_name):
    column_map = {str(c).lower().strip(): c for c in raw_df.columns}

    url_col = None
    for candidate in ["url", "urls", "website", "link"]:
        if candidate in column_map:
            url_col = column_map[candidate]
            break

    label_col = None
    for candidate in ["label", "classlabel", "class", "type", "status", "target"]:
        if candidate in column_map:
            label_col = column_map[candidate]
            break

    if url_col is None or label_col is None:
        print("Skipping", source_name, "- could not find URL/label columns")
        print("Columns:", list(raw_df.columns))
        return pd.DataFrame(columns=["url", "label", "source"])

    out = raw_df[[url_col, label_col]].rename(columns={url_col: "url", label_col: "raw_label"})
    out["url"] = out["url"].astype(str).str.strip()
    out = out.dropna(subset=["url", "raw_label"])

    raw_label = out["raw_label"]
    source_lower = source_name.lower()

    if pd.api.types.is_numeric_dtype(raw_label):
        labels = raw_label.astype(int)
        unique_values = set(labels.dropna().unique().tolist())
        if unique_values.issubset({0, 1}):
            # PhiUSIIL and LegitPhish use 1 = legitimate, 0 = phishing.
            if "phiusiil" in source_lower or "legitphish" in source_lower:
                out["label"] = labels.map({1: 0, 0: 1})
            else:
                out["label"] = labels
        else:
            print("Skipping", source_name, "- unsupported labels:", sorted(unique_values))
            return pd.DataFrame(columns=["url", "label", "source"])
    else:
        text = raw_label.astype(str).str.lower().str.strip()
        unique_text = set(text.dropna().unique().tolist())
        if unique_text.issubset({"0", "1"}):
            if "phiusiil" in source_lower or "legitphish" in source_lower:
                out["label"] = text.map({"1": 0, "0": 1})
            else:
                out["label"] = text.astype(int)
        else:
            mapping = {
                "legitimate": 0, "legit": 0, "benign": 0, "safe": 0, "good": 0,
                "phishing": 1, "phish": 1, "malicious": 1, "bad": 1,
            }
            out["label"] = text.map(mapping)

    out = out[["url", "label"]].dropna()
    out["label"] = out["label"].astype(int)
    out["url"] = out["url"].map(normalize_url)
    out = out.dropna(subset=["url"]).drop_duplicates(subset=["url"])
    out["source"] = source_name

    if len(out) > MAX_OPTIONAL_DATASET_ROWS:
        out = (
            out.groupby("label", group_keys=False)
            .apply(lambda x: x.sample(min(len(x), MAX_OPTIONAL_DATASET_ROWS // 2), random_state=RANDOM_SEED))
            .sample(frac=1.0, random_state=RANDOM_SEED)
            .reset_index(drop=True)
        )
    return out


for name, content in optional_uploads.items():
    if not name.lower().endswith(".csv"):
        continue
    path = DATA_DIR / name
    path.write_bytes(content)
    raw_optional = pd.read_csv(path)
    normalized = normalize_external_dataset(raw_optional, source_name=name)
    if len(normalized):
        frames.append(normalized)
        print("Added optional dataset:", name, len(normalized))

if not frames:
    raise RuntimeError("No training data was loaded.")

dataset = pd.concat(frames, ignore_index=True)
dataset["url"] = dataset["url"].astype(str).str.strip()
dataset = dataset.dropna(subset=["url", "label"])

# Remove exact duplicates while preserving weighted official/synthetic rows by source.
# If the same URL appears with conflicting labels, keep phishing label conservatively.
conflict = dataset.groupby("url")["label"].nunique()
conflict_urls = set(conflict[conflict > 1].index)
if conflict_urls:
    print("Conflicting URL labels found:", len(conflict_urls), "- keeping phishing label for conflicts")
    non_conflict = dataset[~dataset["url"].isin(conflict_urls)]
    conflict_df = dataset[dataset["url"].isin(conflict_urls)].groupby("url", as_index=False).agg({
        "label": "max",
        "source": lambda s: "+".join(sorted(set(map(str, s))))[:200],
    })
    dataset = pd.concat([non_conflict, conflict_df], ignore_index=True)

CRITICAL_SOURCES = {
    "guardy_official_domains",
    "guardy_paypal_official_account_calibration",
    "synthetic_brand_impersonation",
}

if len(dataset) > MAX_TOTAL_TRAINING_ROWS:
    print("Applying source-aware total training row cap:", MAX_TOTAL_TRAINING_ROWS)

    critical = dataset[dataset["source"].isin(CRITICAL_SOURCES)].copy()
    non_critical = dataset[~dataset["source"].isin(CRITICAL_SOURCES)].copy()

    if len(critical) > MAX_TOTAL_TRAINING_ROWS:
        print("Critical rows exceeded total cap; sampling critical rows by source.")
        critical = (
            critical.groupby("source", group_keys=False)
            .apply(lambda g: g.sample(
                min(len(g), max(1, MAX_TOTAL_TRAINING_ROWS // len(CRITICAL_SOURCES))),
                random_state=RANDOM_SEED,
            ))
            .reset_index(drop=True)
        )

    remaining_slots = MAX_TOTAL_TRAINING_ROWS - len(critical)
    if remaining_slots > 0 and len(non_critical):
        target_phishing_total = int(MAX_TOTAL_TRAINING_ROWS * TARGET_PHISHING_RATIO)
        target_legitimate_total = MAX_TOTAL_TRAINING_ROWS - target_phishing_total

        current_counts = critical["label"].value_counts().to_dict()
        need_by_label = {
            0: max(0, target_legitimate_total - int(current_counts.get(0, 0))),
            1: max(0, target_phishing_total - int(current_counts.get(1, 0))),
        }

        sampled_parts = [critical]
        used_indices = set()
        for label in [0, 1]:
            group = non_critical[non_critical["label"] == label]
            take = min(len(group), need_by_label[label], remaining_slots - sum(len(p) for p in sampled_parts[1:]))
            if take > 0:
                sample = group.sample(take, random_state=RANDOM_SEED)
                sampled_parts.append(sample)
                used_indices.update(sample.index.tolist())

        selected_count = sum(len(p) for p in sampled_parts)
        leftover_slots = MAX_TOTAL_TRAINING_ROWS - selected_count
        if leftover_slots > 0:
            leftovers = non_critical[~non_critical.index.isin(used_indices)]
            if len(leftovers):
                sampled_parts.append(leftovers.sample(min(len(leftovers), leftover_slots), random_state=RANDOM_SEED))

        dataset = pd.concat(sampled_parts, ignore_index=True)
    else:
        dataset = critical

    print("Rows after source-aware cap:", len(dataset))
    print("Preserved critical rows:", int(dataset["source"].isin(CRITICAL_SOURCES).sum()))

dataset = dataset.sample(frac=1.0, random_state=RANDOM_SEED).reset_index(drop=True)

print("Final dataset rows:", len(dataset))
display(dataset["label"].value_counts().sort_index().rename(index={0: "legitimate", 1: "phishing"}).to_frame("count"))
display(dataset["source"].value_counts().to_frame("count").head(20))
display(dataset.head())

"""## 7. Backend-Compatible Feature Extraction

This section mirrors the current Guardy backend 39-feature schema:

`FEATURE_NAMES_USED = FEATURE_NAMES without uses_https`

That makes the exported model a drop-in replacement for `backend/ml/model.pkl`.
"""

SUSPICIOUS_TLDS = {
    ".xyz", ".tk", ".ml", ".ga", ".cf", ".gq", ".top", ".club", ".work",
    ".click", ".link", ".download", ".win", ".loan", ".racing", ".party",
    ".stream", ".trade", ".science", ".date", ".cc", ".pw", ".icu", ".cyou",
    ".monster", ".buzz", ".surf", ".casa", ".rest", ".ru", ".cn", ".xin",
    ".bond", ".help", ".cfd", ".lol", ".sbs", ".support", ".li", ".info", ".vip",
}

SHORTENERS = {
    "bit.ly", "tinyurl.com", "t.co", "goo.gl", "ow.ly", "is.gd", "buff.ly",
    "adf.ly", "short.link", "rebrand.ly", "tiny.cc", "cutt.ly", "rb.gy",
    "shorturl.at", "bl.ink", "snip.ly", "clck.ru", "qps.ru", "u.to", "t.ly",
    "qrco.de", "goo.su", "zzb.bz", "x.co", "lnkd.in", "youtu.be", "forms.gle",
    "linktr.ee",
}

SUSPICIOUS_KEYWORDS = [
    "login", "verify", "account", "update", "secure", "banking", "confirm",
    "paypal", "ebay", "amazon", "apple", "microsoft", "google", "signin",
    "password", "credential", "reset", "suspend", "validate", "urgent",
    "billing", "payment", "invoice", "verification", "authenticate",
    "authorization", "unlock", "reactivate", "recover", "restore", "alert",
    "notice", "limited", "expire", "expir", "unusual", "suspicious", "wallet",
    "crypto", "bitcoin", "transfer", "refund", "transaction", "checkout",
    "carddetails", "cvv", "iban", "ssn", "support", "helpdesk", "webscr",
    "cmd", "redirect", "toll", "tracking", "delivery", "parcel", "dhl",
    "fedex", "usps", "ups", "netflix", "spotify", "steam", "prize", "winner",
    "claim", "security", "2fa", "otp", "icloud", "dropbox", "onedrive",
    "wellsfargo", "chase", "barclays", "hsbc", "webmail", "cpanel",
    "roundcube", "token", "session", "auth",
]

# Extend brand keywords with Guardy's actual registry while preserving backend semantics.
BRAND_KEYWORDS = sorted(set([
    "paypal", "chase", "wellsfargo", "barclays", "hsbc", "citibank",
    "bankofamerica", "usbank", "capitalone", "deutschebank", "santander",
    "natwest", "lloyds", "halifax", "ing", "bnpparibas", "visa", "mastercard",
    "americanexpress", "amex", "google", "microsoft", "apple", "amazon",
    "facebook", "meta", "instagram", "twitter", "linkedin", "youtube", "tiktok",
    "whatsapp", "telegram", "discord", "snapchat", "pinterest", "reddit",
    "tumblr", "twitch", "dropbox", "icloud", "onedrive", "googledrive", "box",
    "sharepoint", "wetransfer", "ebay", "etsy", "shopify", "aliexpress",
    "alibaba", "wish", "walmart", "target", "bestbuy", "ikea", "netflix",
    "spotify", "hulu", "disneyplus", "disney", "hbomax", "paramount", "steam",
    "epicgames", "playstation", "xbox", "roblox", "outlook", "office365",
    "gmail", "yahoo", "zoho", "docusign", "adobe", "notion", "slack", "zoom",
    "dhl", "fedex", "usps", "ups", "royalmail", "dpd", "hermes", "evri",
    "purolator", "coinbase", "binance", "kraken", "metamask", "blockchain",
    "robinhood", "revolut", "cashapp", "venmo", "zelle", "att", "verizon",
    "tmobile", "sprint", "comcast", "xfinity", "vodafone", "orange", "o2",
    "bt", "irs", "gov", "hmrc", "medicare", "socialsecurity",
] + brand_keywords))

SUSPICIOUS_EXTENSIONS = (
    ".exe", ".zip", ".rar", ".js", ".php", ".bat", ".cmd", ".scr", ".msi",
    ".apk", ".dmg", ".ps1", ".vbs",
)

VOWELS = set("aeiou")

FEATURE_NAMES = [
    "length_url", "length_hostname", "nb_hyphens", "nb_dots", "nb_digits",
    "entropy", "full_entropy", "nb_at", "nb_special_chars", "url_digit_ratio",
    "url_symbol_ratio", "vowel_ratio", "nb_repeated_chars", "url_length_suspicious",
    "nb_subdomains", "ip", "punycode", "domain_digit_ratio", "long_domain",
    "nb_consecutive_digits", "subdomain_is_ip", "has_www", "suspicious_tld",
    "tld_length", "length_path", "path_depth", "nb_params", "query_length",
    "has_suspicious_ext", "suspicious_keywords", "domain_has_brand",
    "brand_in_path", "brand_is_domain", "has_hex_encoding", "https_in_path",
    "nb_double_slash", "nb_redirects", "uses_https", "shortening_service",
    "has_suspicious_port",
]

FEATURE_NAMES_USED = [name for name in FEATURE_NAMES if name != "uses_https"]


def shannon_entropy(value):
    if not value:
        return 0.0
    counts = Counter(value)
    length = len(value)
    return -sum((count / length) * math.log2(count / length) for count in counts.values())


def split_hostname(hostname):
    parts = [part for part in hostname.split(".") if part]
    if len(parts) >= 2:
        domain = parts[-2]
        suffix = parts[-1]
        subdomain = ".".join(parts[:-2])
        return domain, suffix, subdomain
    return hostname, "", ""


def extract_features(url):
    try:
        raw_url = str(url).strip()
        parsed = urlparse(normalize_url(raw_url))
        hostname = (parsed.hostname or "").lower()
        domain, suffix_value, subdomain = split_hostname(hostname)
        suffix = f".{suffix_value}" if suffix_value else ""
        path = parsed.path or ""
        query = parsed.query or ""
        full_path = f"{path}?{query}" if query else path

        clean_sub = re.sub(r"^www\\.?", "", subdomain)
        nb_subdomains = len(clean_sub.split(".")) if clean_sub else 0
        length_url = len(raw_url)
        length_hostname = len(hostname)
        nb_hyphens = domain.count("-")
        nb_dots = hostname.count(".")
        nb_digits = sum(char.isdigit() for char in domain)
        entropy = round(shannon_entropy(domain), 4)
        full_entropy = round(shannon_entropy(raw_url), 4)
        nb_at = raw_url.count("@")
        nb_special_chars = sum(raw_url.count(char) for char in ["%", "=", "&", "?", "#"])
        url_digit_ratio = round(sum(char.isdigit() for char in raw_url) / max(len(raw_url), 1), 4)
        url_symbol_ratio = round(len(re.findall(r"[^a-zA-Z0-9]", raw_url)) / max(len(raw_url), 1), 4)
        vowel_ratio = round(sum(char in VOWELS for char in domain.lower()) / max(len(domain), 1), 4)
        nb_repeated_chars = len(re.findall(r"(.)\\1{2,}", domain))
        url_length_suspicious = 1 if length_url > 100 else 0
        ip = 1 if re.match(r"^\\d{1,3}(\\.\\d{1,3}){3}$", hostname) else 0
        punycode = 1 if "xn--" in raw_url.lower() else 0
        domain_digit_ratio = round(nb_digits / max(len(domain), 1), 3)
        long_domain = 1 if len(domain) > 20 else 0
        nb_consecutive_digits = len(re.findall(r"\\d{4,}", hostname))
        subdomain_is_ip = 1 if re.match(r"^\\d{1,3}\\.\\d{1,3}", subdomain) else 0
        has_www = 1 if hostname.startswith("www.") else 0
        suspicious_tld = 1 if suffix.lower() in SUSPICIOUS_TLDS else 0
        tld_length = len(suffix_value) if suffix_value else 0
        length_path = len(path)
        path_depth = path.count("/")
        nb_params = len(re.findall(r"[?&][^=&]+=?[^&]*", raw_url))
        query_length = len(query)
        has_suspicious_ext = 1 if any(path.lower().endswith(ext) for ext in SUSPICIOUS_EXTENSIONS) else 0
        full_path_lower = full_path.lower()
        hostname_lower = hostname.lower()
        suspicious_keywords = sum(1 for keyword in SUSPICIOUS_KEYWORDS if keyword in full_path_lower)
        domain_has_brand = 1 if any(brand in hostname_lower for brand in BRAND_KEYWORDS) else 0
        brand_in_path = 1 if any(brand in full_path_lower for brand in BRAND_KEYWORDS) else 0
        brand_is_domain = 1 if any(brand == domain.lower() for brand in BRAND_KEYWORDS) else 0
        has_hex_encoding = 1 if re.search(r"%[0-9a-fA-F]{2}", raw_url) else 0
        https_in_path = 1 if "https" in path.lower() else 0
        nb_double_slash = max(0, raw_url.count("//") - 1)
        nb_redirects = max(0, len(re.findall(r"https?://", raw_url)) - 1)
        uses_https = 1 if parsed.scheme == "https" else 0
        shortening_service = 1 if hostname_lower in SHORTENERS else 0
        has_suspicious_port = 1 if re.search(r":\\d{4,5}/", raw_url) else 0

        return [
            length_url, length_hostname, nb_hyphens, nb_dots, nb_digits, entropy,
            full_entropy, nb_at, nb_special_chars, url_digit_ratio, url_symbol_ratio,
            vowel_ratio, nb_repeated_chars, url_length_suspicious, nb_subdomains, ip,
            punycode, domain_digit_ratio, long_domain, nb_consecutive_digits,
            subdomain_is_ip, has_www, suspicious_tld, tld_length, length_path,
            path_depth, nb_params, query_length, has_suspicious_ext,
            suspicious_keywords, domain_has_brand, brand_in_path, brand_is_domain,
            has_hex_encoding, https_in_path, nb_double_slash, nb_redirects, uses_https,
            shortening_service, has_suspicious_port,
        ]
    except Exception:
        return [0] * len(FEATURE_NAMES)


def extract_model_features(url):
    features = dict(zip(FEATURE_NAMES, extract_features(url), strict=False))
    return [features[name] for name in FEATURE_NAMES_USED]


def features_to_frame(urls):
    rows = [extract_model_features(url) for url in urls]
    return pd.DataFrame(rows, columns=FEATURE_NAMES_USED).fillna(0.0).astype(float)


print("Feature count:", len(FEATURE_NAMES_USED))
print(FEATURE_NAMES_USED)

start = time.time()
X = features_to_frame(dataset["url"].tolist())
y = dataset["label"].astype(int).values
print("Feature extraction seconds:", round(time.time() - start, 1))
print(X.shape)
display(X.head())

"""## 8. Train/Test Split

The split is stratified. Source labels remain available for source-level analysis.
"""

X_train, X_test, y_train, y_test, train_meta, test_meta = train_test_split(
    X,
    y,
    dataset[["url", "source"]].reset_index(drop=True),
    test_size=0.20,
    random_state=RANDOM_SEED,
    stratify=y,
)

print("Train:", X_train.shape, "Test:", X_test.shape)
display(pd.Series(y_train).value_counts().sort_index().rename(index={0: "legitimate", 1: "phishing"}).to_frame("train_count"))
display(pd.Series(y_test).value_counts().sort_index().rename(index={0: "legitimate", 1: "phishing"}).to_frame("test_count"))

"""## 9. Train And Compare Models

Models:

- Logistic Regression
- Random Forest
- ExtraTrees
- XGBoost

The selected model prioritizes phishing recall while controlling false positives.
"""

models = {
    "Logistic Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LogisticRegression(max_iter=1000, class_weight="balanced", random_state=RANDOM_SEED, n_jobs=-1)),
    ]),
    "Random Forest": RandomForestClassifier(
        n_estimators=300,
        min_samples_leaf=2,
        class_weight="balanced_subsample",
        random_state=RANDOM_SEED,
        n_jobs=-1,
    ),
    "ExtraTrees": ExtraTreesClassifier(
        n_estimators=400,
        min_samples_leaf=2,
        class_weight="balanced",
        random_state=RANDOM_SEED,
        n_jobs=-1,
    ),
    "XGBoost": XGBClassifier(
        n_estimators=500,
        max_depth=6,
        learning_rate=0.06,
        subsample=0.9,
        colsample_bytree=0.9,
        objective="binary:logistic",
        eval_metric="logloss",
        random_state=RANDOM_SEED,
        n_jobs=-1,
        tree_method="hist",
    ),
}


def proba_phishing(model, X_values):
    proba = model.predict_proba(X_values)
    return proba[:, 1] if getattr(proba, "ndim", 1) == 2 else np.asarray(proba).ravel()


def false_positive_rate(y_true, y_pred):
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()
    return fp / max(fp + tn, 1)


def manual_cross_validate(estimator, X_values, y_values, cv):
    """Manual CV avoids sklearn cross_validate calling broken XGBoost sklearn tags."""
    fold_rows = []
    for fold, (train_idx, valid_idx) in enumerate(cv.split(X_values, y_values), start=1):
        model = copy.deepcopy(estimator)
        X_fold_train = X_values.iloc[train_idx] if hasattr(X_values, "iloc") else X_values[train_idx]
        X_fold_valid = X_values.iloc[valid_idx] if hasattr(X_values, "iloc") else X_values[valid_idx]
        y_fold_train = y_values[train_idx]
        y_fold_valid = y_values[valid_idx]

        model.fit(X_fold_train, y_fold_train)
        prob = proba_phishing(model, X_fold_valid)
        pred = (prob >= 0.5).astype(int)
        fold_rows.append({
            "fold": fold,
            "f1": f1_score(y_fold_valid, pred, zero_division=0),
            "precision": precision_score(y_fold_valid, pred, zero_division=0),
            "recall": recall_score(y_fold_valid, pred, zero_division=0),
            "roc_auc": roc_auc_score(y_fold_valid, prob),
        })
    return pd.DataFrame(fold_rows)


cv = StratifiedKFold(n_splits=CV_SPLITS, shuffle=True, random_state=RANDOM_SEED)
cv_rows = []
for name, model in models.items():
    print("Cross-validating", name)
    scores = manual_cross_validate(model, X_train, y_train, cv)
    cv_rows.append({
        "model": name,
        "cv_f1": scores["f1"].mean(),
        "cv_precision": scores["precision"].mean(),
        "cv_recall": scores["recall"].mean(),
        "cv_roc_auc": scores["roc_auc"].mean(),
    })

cv_results = pd.DataFrame(cv_rows).sort_values(["cv_f1", "cv_recall", "cv_roc_auc"], ascending=False)
display(cv_results)

fitted = {}
rows = []
for name, model in models.items():
    print("Training", name)
    model.fit(X_train, y_train)
    fitted[name] = model
    prob = proba_phishing(model, X_test)
    pred = (prob >= 0.5).astype(int)
    rows.append({
        "model": name,
        "accuracy": accuracy_score(y_test, pred),
        "precision": precision_score(y_test, pred, zero_division=0),
        "recall": recall_score(y_test, pred, zero_division=0),
        "f1": f1_score(y_test, pred, zero_division=0),
        "roc_auc": roc_auc_score(y_test, prob),
        "false_positive_rate": false_positive_rate(y_test, pred),
    })

test_results = pd.DataFrame(rows).sort_values(
    ["f1", "recall", "roc_auc", "false_positive_rate"],
    ascending=[False, False, False, True],
)
display(test_results)

best_model_name = test_results.iloc[0]["model"]
best_model = fitted[best_model_name]
best_prob = proba_phishing(best_model, X_test)
print("Selected model:", best_model_name)

"""## 10. Evaluation And Manual Guardy Checks"""

default_pred = (best_prob >= 0.5).astype(int)
print(classification_report(y_test, default_pred, target_names=["legitimate", "phishing"], digits=4))

cm = confusion_matrix(y_test, default_pred, labels=[0, 1])
plt.figure(figsize=(5, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=["legitimate", "phishing"], yticklabels=["legitimate", "phishing"])
plt.title("Confusion Matrix @ 0.5")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

source_eval = test_meta.copy().reset_index(drop=True)
source_eval["label"] = y_test
source_eval["probability"] = best_prob
source_eval["prediction"] = default_pred
source_rows = []
for source, group in source_eval.groupby("source"):
    source_rows.append({
        "source": source,
        "rows": len(group),
        "positive_rate": group["label"].mean(),
        "error_rate": (group["label"] != group["prediction"]).mean(),
        "mean_probability": group["probability"].mean(),
    })
display(pd.DataFrame(source_rows).sort_values("rows", ascending=False).head(30))

safe_urls = [
    "https://www.google.com",
    "https://www.paypal.com/signin",
    "https://www.paypal.com/myaccount/summary",
    "https://www.paypal.com/myaccount/security",
    "https://www.microsoft.com",
    "https://www.apple.com",
    "https://www.swedbank.lt",
    "https://www.seb.lt",
    "https://www.revolut.com",
    "https://bank.paysera.com",
]

phishing_like_urls = [
    "http://paypal-secure-login.xyz/verify?account=1",
    "http://microsoft-security-update.xyz",
    "http://dhl-tracking-update.xyz",
    "http://binance-wallet-verify.xyz",
    "http://mbank-login-secure.xyz",
    "http://swedbank-login-secure.xyz",
    "http://paysera-account-verify.xyz",
    "http://192.168.1.1/login/verify",
    "http://xn--pypal-4va.com/login",
]

manual_df = pd.DataFrame({
    "url": safe_urls + phishing_like_urls,
    "expected_group": ["safe"] * len(safe_urls) + ["phishing-like"] * len(phishing_like_urls),
})
manual_X = features_to_frame(manual_df["url"].tolist())
manual_df["probability"] = proba_phishing(best_model, manual_X)
manual_df["pred_0_5"] = (manual_df["probability"] >= 0.5).astype(int)
manual_df["manual_check"] = np.where(
    (manual_df["expected_group"] == "safe") & (manual_df["pred_0_5"] == 1),
    "SAFE FALSE POSITIVE - do not deploy",
    np.where((manual_df["expected_group"] == "phishing-like") & (manual_df["pred_0_5"] == 0), "PHISHING FALSE NEGATIVE - review", "ok"),
)
display(manual_df)

MANUAL_SANITY_PASSED = (manual_df["manual_check"] == "ok").all()
print("Manual sanity passed:", MANUAL_SANITY_PASSED)

"""## 11. Threshold Selection"""

thresholds = [0.2, 0.3, 0.4, 0.5, 0.6, 0.7]
threshold_rows = []
for threshold in thresholds:
    pred = (best_prob >= threshold).astype(int)
    threshold_rows.append({
        "threshold": threshold,
        "accuracy": accuracy_score(y_test, pred),
        "precision": precision_score(y_test, pred, zero_division=0),
        "recall": recall_score(y_test, pred, zero_division=0),
        "f1": f1_score(y_test, pred, zero_division=0),
        "roc_auc": roc_auc_score(y_test, best_prob),
        "false_positive_rate": false_positive_rate(y_test, pred),
    })

threshold_df = pd.DataFrame(threshold_rows)
display(threshold_df)

candidates = threshold_df[threshold_df["recall"] >= 0.98]
if len(candidates):
    selected = candidates.sort_values(["false_positive_rate", "f1"], ascending=[True, False]).iloc[0]
else:
    selected = threshold_df.sort_values(["f1", "false_positive_rate"], ascending=[False, True]).iloc[0]

SELECTED_THRESHOLD = float(selected["threshold"])
print("Selected threshold:", SELECTED_THRESHOLD)

"""## 12. Export Backend-Compatible Model

"""

SELECTED_THRESHOLD = 0.4
CONSERVATIVE_THRESHOLD = 0.7

if not MANUAL_SANITY_PASSED:
    raise RuntimeError("Manual Guardy sanity checks failed. Do not export/deploy this model yet.")

selected_pred = (best_prob >= SELECTED_THRESHOLD).astype(int)
conservative_pred = (best_prob >= CONSERVATIVE_THRESHOLD).astype(int)

metrics = {
    "accuracy": float(accuracy_score(y_test, selected_pred)),
    "precision": float(precision_score(y_test, selected_pred, zero_division=0)),
    "recall": float(recall_score(y_test, selected_pred, zero_division=0)),
    "f1": float(f1_score(y_test, selected_pred, zero_division=0)),
    "roc_auc": float(roc_auc_score(y_test, best_prob)),
    "false_positive_rate": float(false_positive_rate(y_test, selected_pred)),
}

conservative_metrics = {
    "accuracy": float(accuracy_score(y_test, conservative_pred)),
    "precision": float(precision_score(y_test, conservative_pred, zero_division=0)),
    "recall": float(recall_score(y_test, conservative_pred, zero_division=0)),
    "f1": float(f1_score(y_test, conservative_pred, zero_division=0)),
    "roc_auc": float(roc_auc_score(y_test, best_prob)),
    "false_positive_rate": float(false_positive_rate(y_test, conservative_pred)),
}

model_path = EXPORT_DIR / "model.pkl"
hybrid_model_path = EXPORT_DIR / "guardy_hybrid_model.pkl"
joblib_model_path = EXPORT_DIR / "guardy_hybrid_model.joblib"
feature_names_path = EXPORT_DIR / "feature_names.json"
metadata_path = EXPORT_DIR / "model_metadata.json"

# The current Guardy backend uses pickle.load(), so model.pkl must be written
# with pickle.dump(), not joblib.dump(). A joblib copy is exported only for analysis.
with model_path.open("wb") as file:
    pickle.dump(best_model, file)

with hybrid_model_path.open("wb") as file:
    pickle.dump(best_model, file)

joblib.dump(best_model, joblib_model_path)

feature_names_path.write_text(json.dumps(FEATURE_NAMES_USED, indent=2), encoding="utf-8")

metadata = {
    "model_type": best_model_name,
    "training_date": datetime.now(timezone.utc).isoformat(),
    "backend_compatible_39_features": BACKEND_COMPATIBLE_39,
    "dataset_sources": sorted(dataset["source"].unique().tolist()),
    "number_of_samples": int(len(dataset)),
    "number_of_phishing_samples": int((dataset["label"] == 1).sum()),
    "number_of_legitimate_samples": int((dataset["label"] == 0).sum()),
    "feature_count": int(len(FEATURE_NAMES_USED)),

    "selected_threshold": SELECTED_THRESHOLD,
    "recommended_threshold": 0.4,
    "conservative_threshold": CONSERVATIVE_THRESHOLD,
    "threshold_policy": {
        "0.4": "recommended for Guardy: better phishing recall with still very low false positive rate",
        "0.7": "conservative mode: fewer false positives but slightly lower phishing recall"
    },

    "metrics": metrics,
    "conservative_metrics": conservative_metrics,
    "manual_guardy_checks": manual_df.to_dict(orient="records"),
}

metadata_path.write_text(json.dumps(metadata, indent=2), encoding="utf-8")

native_path = None
if best_model_name == "XGBoost":
    native_path = EXPORT_DIR / "xgboost_model.json"
    best_model.save_model(str(native_path))

print("Exported:")
print(model_path)
print(hybrid_model_path)
print(joblib_model_path)
print(feature_names_path)
print(metadata_path)
if native_path:
    print(native_path)

display(metadata)

for path in [model_path, hybrid_model_path, joblib_model_path, feature_names_path, metadata_path] + ([native_path] if native_path else []):
    files.download(str(path))

# Hybrid model manual test charts
# Run after training, evaluation, and manual feature functions are already loaded.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

HYBRID_THRESHOLDS = [0.4, 0.5, 0.7]

safe_urls = [
    # Lithuanian banks / finance
    "https://www.seb.lt/privatiems/kasdiene-bankininkyste/nuotolines-paslaugos/interneto-bankas",
    "https://e.seb.lt",
    "https://www.swedbank.lt",
    "https://www.swedbank.lt/private",
    "https://ib.swedbank.lt/private",
    "https://www.luminor.lt/lt/privatiems/interneto-bankas",
    "https://www.luminor.lt/en/private/internet-bank",
    "https://online.citadele.lv/ibbf/lt_lt",
    "https://www.paysera.lt",
    "https://bank.paysera.com",
    "https://www.revolut.com",
    "https://app.revolut.com/start",

    # Lithuanian e-commerce / services
    "https://www.senukai.lt",
    "https://www.senukai.lt/c/kompiuterine-technika-biuro-prekes/stacionarus-kompiuteriai-monitoriai-ups/stacionarus-kompiuteriai/c07",
    "https://www.skytech.lt",
    "https://www.skytech.lt/akcoregamerpropbar59-asmeninio-komp-komplektas-core-gamer-pro-powered-asus-intel-p-814209.html",
    "https://pigu.lt",
    "https://www.pigu.lt/lt/",
    "https://www.varle.lt",
    "https://www.varle.lt/nesiojami-kompiuteriai/",
    "https://www.skelbiu.lt",
    "https://www.vinted.lt",
    "https://www.lpexpress.lt",
    "https://www.post.lt",
    "https://venipak.com",
    "https://www.dpd.com/lt/lt/",
    "https://www.omniva.lt",

    # Telecom / utilities
    "https://www.telia.lt",
    "https://www.tele2.lt",
    "https://www.bite.lt",
    "https://ignitis.lt",

    # Global official login/account pages
    "https://www.google.com",
    "https://accounts.google.com/signin",
    "https://www.microsoft.com",
    "https://login.microsoftonline.com",
    "https://www.apple.com",
    "https://appleid.apple.com/sign-in",
    "https://www.paypal.com/signin",
    "https://www.paypal.com/myaccount/summary",
    "https://www.paypal.com/myaccount/security",
    "https://www.roblox.com/login",
    "https://github.com/login",
    "https://www.netflix.com/login",
    "https://www.amazon.com",
]

phishing_urls = [
    "https://xtic.live-lanboesports.com/",
    "https://verificadorbhd.viafirmas.com",
    "http://kzbi.bdhjwjpn.baby",
    "https://havanshop.shop/",
    "https://seguro.redemegaobra.com.br/Z-DNTNM93H3SGNUFEP",
    "https://carloseletro.site/",
    "https://www.cabinetsanything.com/",
    "http://cabinetsanything.com",
    "https://viomnsd.shop/",
    "https://mail.desenrolabrasil.org/",
    "https://gerenciadorgov.com/",
    "https://floricultura.resgate.is/",
    "https://io-apps-dydaax.wixstudio.com:443/en-us",
    "https://bill-meta.program-ads-agency.com/",
    "http://bill-meta.program-ads-agency.com",
    "https://business-meta.accounts-admin-agency.com/",
    "http://business-meta.accounts-admin-agency.com",
    "https://goes326-goutian-bc.pages.dev/help/contact/206000278552756",
    "http://goes326-goutian-bc.pages.dev/help/contact/206000278552756",
    "https://instagram-copy.vercel.app/",
    "https://allegro.smarp2932-h5.lat",
    "https://leger-liv-acces.wixstudio.com/setup",
    "https://best-desktop.wixstudio.com/en-us",
    "https://home-started.wixstudio.com/web-us",
    "https://commande-maladie.com/",
    "https://www.commande-maladie.com/",
    "https://eu-pp.com/",
    "https://eu-pp.com/index.php",
    "http://votrportail-administratiffr-ticketad2410-3892.wpdevcloud.com/zuse.html",
    "https://votrportail-administratiffr-ticketad2410-3892.wpdevcloud.com/wp-admin/adusart/redirect",
    "http://paypal-secure-login.xyz/verify?account=1",
    "http://microsoft-security-update.xyz",
    "http://dhl-tracking-update.xyz",
    "http://binance-wallet-verify.xyz",
    "http://mbank-login-secure.xyz",
    "http://swedbank-login-secure.xyz",
    "http://paysera-account-verify.xyz",
    "http://192.168.1.1/login/verify",
    "http://xn--pypal-4va.com/login",
]

hybrid_manual_df = pd.DataFrame({
    "url": safe_urls + phishing_urls,
    "expected_group": ["safe"] * len(safe_urls) + ["phishing"] * len(phishing_urls),
    "label": [0] * len(safe_urls) + [1] * len(phishing_urls),
})

X_manual = features_to_frame(hybrid_manual_df["url"].tolist())
hybrid_manual_df["phishing_probability"] = proba_phishing(best_model, X_manual)

for threshold in HYBRID_THRESHOLDS:
    suffix = str(threshold).replace(".", "_")
    hybrid_manual_df[f"pred_{suffix}"] = (
        hybrid_manual_df["phishing_probability"] >= threshold
    ).astype(int)

display(hybrid_manual_df)

# Summary by threshold
summary_rows = []

for threshold in HYBRID_THRESHOLDS:
    suffix = str(threshold).replace(".", "_")
    pred_col = f"pred_{suffix}"

    safe_mask = hybrid_manual_df["label"] == 0
    phish_mask = hybrid_manual_df["label"] == 1

    summary_rows.append({
        "threshold": threshold,
        "safe_false_positives": int(((hybrid_manual_df[pred_col] == 1) & safe_mask).sum()),
        "phishing_false_negatives": int(((hybrid_manual_df[pred_col] == 0) & phish_mask).sum()),
        "safe_total": int(safe_mask.sum()),
        "phishing_total": int(phish_mask.sum()),
        "safe_mean_probability": float(hybrid_manual_df.loc[safe_mask, "phishing_probability"].mean()),
        "phishing_mean_probability": float(hybrid_manual_df.loc[phish_mask, "phishing_probability"].mean()),
        "accuracy": float((hybrid_manual_df[pred_col] == hybrid_manual_df["label"]).mean()),
    })

hybrid_summary_df = pd.DataFrame(summary_rows)
display(hybrid_summary_df)

# Chart 1: probability distribution by class
plt.figure(figsize=(9, 5))
sns.boxplot(
    data=hybrid_manual_df,
    x="expected_group",
    y="phishing_probability",
)
for threshold, color in [(0.4, "orange"), (0.5, "red"), (0.7, "purple")]:
    plt.axhline(threshold, color=color, linestyle="--", linewidth=1.2, label=f"threshold {threshold}")
plt.ylim(0, 1)
plt.title("Hybrid model phishing probability by manual label")
plt.xlabel("")
plt.ylabel("Phishing probability")
plt.legend()
plt.show()

# Chart 2: error counts by threshold
error_rows = []
for threshold in HYBRID_THRESHOLDS:
    suffix = str(threshold).replace(".", "_")
    pred_col = f"pred_{suffix}"

    safe_fp = int(((hybrid_manual_df[pred_col] == 1) & (hybrid_manual_df["label"] == 0)).sum())
    phish_fn = int(((hybrid_manual_df[pred_col] == 0) & (hybrid_manual_df["label"] == 1)).sum())

    error_rows.append({"threshold": threshold, "error_type": "safe false positives", "count": safe_fp})
    error_rows.append({"threshold": threshold, "error_type": "phishing false negatives", "count": phish_fn})

error_df = pd.DataFrame(error_rows)

plt.figure(figsize=(9, 5))
sns.barplot(data=error_df, x="threshold", y="count", hue="error_type")
plt.title("Hybrid model manual test errors by threshold")
plt.xlabel("Threshold")
plt.ylabel("Error count")
plt.show()

# Chart 3: URL-level heatmap
heatmap_df = hybrid_manual_df[["url", "expected_group", "phishing_probability"]].copy()
heatmap_df["short_url"] = (
    heatmap_df["url"]
    .str.replace("https://", "", regex=False)
    .str.replace("http://", "", regex=False)
    .str.slice(0, 85)
)
heatmap_df["label_prefix"] = np.where(heatmap_df["expected_group"] == "safe", "SAFE: ", "PHISH: ")
heatmap_df["display_url"] = heatmap_df["label_prefix"] + heatmap_df["short_url"]

heatmap_numeric = heatmap_df[["phishing_probability"]].copy()
heatmap_numeric.index = heatmap_df["display_url"]

plt.figure(figsize=(5, max(8, len(heatmap_numeric) * 0.28)))
sns.heatmap(
    heatmap_numeric.astype(float),
    annot=True,
    fmt=".3f",
    cmap="RdYlGn_r",
    vmin=0,
    vmax=1,
    linewidths=0.2,
    cbar_kws={"label": "Phishing probability"},
)
plt.title("Hybrid model URL-level phishing probabilities")
plt.xlabel("")
plt.ylabel("")
plt.show()

# Mistakes per threshold
for threshold in HYBRID_THRESHOLDS:
    suffix = str(threshold).replace(".", "_")
    pred_col = f"pred_{suffix}"

    mistakes = hybrid_manual_df[hybrid_manual_df[pred_col] != hybrid_manual_df["label"]][
        ["url", "expected_group", "phishing_probability", pred_col]
    ]

    print(f"\nMistakes at threshold {threshold}: {len(mistakes)}")
    display(mistakes)

"""# Hybrid model manual test charts"""

# Hybrid model manual test charts
# Focus: how good the model is, false positives, false negatives.
# Run after training, evaluation, best_model, features_to_frame(), and proba_phishing() exist.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

DECISION_THRESHOLD = 0.5

safe_urls = [
    # Lithuanian banks / finance
    "https://www.seb.lt/privatiems/kasdiene-bankininkyste/nuotolines-paslaugos/interneto-bankas",
    "https://e.seb.lt",
    "https://www.swedbank.lt",
    "https://www.swedbank.lt/private",
    "https://ib.swedbank.lt/private",
    "https://www.luminor.lt/lt/privatiems/interneto-bankas",
    "https://www.luminor.lt/en/private/internet-bank",
    "https://online.citadele.lv/ibbf/lt_lt",
    "https://www.paysera.lt",
    "https://bank.paysera.com",
    "https://www.revolut.com",
    "https://app.revolut.com/start",

    # Lithuanian e-commerce / services
    "https://www.senukai.lt",
    "https://www.senukai.lt/c/kompiuterine-technika-biuro-prekes/stacionarus-kompiuteriai-monitoriai-ups/stacionarus-kompiuteriai/c07",
    "https://www.skytech.lt",
    "https://www.skytech.lt/akcoregamerpropbar59-asmeninio-komp-komplektas-core-gamer-pro-powered-asus-intel-p-814209.html",
    "https://pigu.lt",
    "https://www.pigu.lt/lt/",
    "https://www.varle.lt",
    "https://www.varle.lt/nesiojami-kompiuteriai/",
    "https://www.skelbiu.lt",
    "https://www.vinted.lt",
    "https://www.lpexpress.lt",
    "https://www.post.lt",
    "https://venipak.com",
    "https://www.dpd.com/lt/lt/",
    "https://www.omniva.lt",

    # Telecom / utilities
    "https://www.telia.lt",
    "https://www.tele2.lt",
    "https://www.bite.lt",
    "https://ignitis.lt",

    # Global official login/account pages
    "https://www.google.com",
    "https://accounts.google.com/signin",
    "https://www.microsoft.com",
    "https://login.microsoftonline.com",
    "https://www.apple.com",
    "https://appleid.apple.com/sign-in",
    "https://www.paypal.com/signin",
    "https://www.paypal.com/myaccount/summary",
    "https://www.paypal.com/myaccount/security",
    "https://www.roblox.com/login",
    "https://github.com/login",
    "https://www.netflix.com/login",
    "https://www.amazon.com",
]

phishing_urls = [
    "https://xtic.live-lanboesports.com/",
    "https://verificadorbhd.viafirmas.com",
    "http://kzbi.bdhjwjpn.baby",
    "https://havanshop.shop/",
    "https://seguro.redemegaobra.com.br/Z-DNTNM93H3SGNUFEP",
    "https://carloseletro.site/",
    "https://www.cabinetsanything.com/",
    "http://cabinetsanything.com",
    "https://viomnsd.shop/",
    "https://mail.desenrolabrasil.org/",
    "https://gerenciadorgov.com/",
    "https://floricultura.resgate.is/",
    "https://io-apps-dydaax.wixstudio.com:443/en-us",
    "https://bill-meta.program-ads-agency.com/",
    "http://bill-meta.program-ads-agency.com",
    "https://business-meta.accounts-admin-agency.com/",
    "http://business-meta.accounts-admin-agency.com",
    "https://goes326-goutian-bc.pages.dev/help/contact/206000278552756",
    "http://goes326-goutian-bc.pages.dev/help/contact/206000278552756",
    "https://instagram-copy.vercel.app/",
    "https://allegro.smarp2932-h5.lat",
    "https://leger-liv-acces.wixstudio.com/setup",
    "https://best-desktop.wixstudio.com/en-us",
    "https://home-started.wixstudio.com/web-us",
    "https://commande-maladie.com/",
    "https://www.commande-maladie.com/",
    "https://eu-pp.com/",
    "https://eu-pp.com/index.php",
    "http://votrportail-administratiffr-ticketad2410-3892.wpdevcloud.com/zuse.html",
    "https://votrportail-administratiffr-ticketad2410-3892.wpdevcloud.com/wp-admin/adusart/redirect",
    "http://paypal-secure-login.xyz/verify?account=1",
    "http://microsoft-security-update.xyz",
    "http://dhl-tracking-update.xyz",
    "http://binance-wallet-verify.xyz",
    "http://mbank-login-secure.xyz",
    "http://swedbank-login-secure.xyz",
    "http://paysera-account-verify.xyz",
    "http://192.168.1.1/login/verify",
    "http://xn--pypal-4va.com/login",
]

hybrid_manual_df = pd.DataFrame({
    "url": safe_urls + phishing_urls,
    "expected_group": ["safe"] * len(safe_urls) + ["phishing"] * len(phishing_urls),
    "label": [0] * len(safe_urls) + [1] * len(phishing_urls),
})

X_manual = features_to_frame(hybrid_manual_df["url"].tolist())
hybrid_manual_df["phishing_probability"] = proba_phishing(best_model, X_manual)
hybrid_manual_df["prediction"] = (hybrid_manual_df["phishing_probability"] >= DECISION_THRESHOLD).astype(int)

hybrid_manual_df["prediction_label"] = np.where(
    hybrid_manual_df["prediction"] == 1,
    "phishing",
    "safe",
)

hybrid_manual_df["result"] = np.select(
    [
        (hybrid_manual_df["label"] == 0) & (hybrid_manual_df["prediction"] == 0),
        (hybrid_manual_df["label"] == 1) & (hybrid_manual_df["prediction"] == 1),
        (hybrid_manual_df["label"] == 0) & (hybrid_manual_df["prediction"] == 1),
        (hybrid_manual_df["label"] == 1) & (hybrid_manual_df["prediction"] == 0),
    ],
    [
        "true negative",
        "true positive",
        "false positive",
        "false negative",
    ],
    default="unknown",
)

display(hybrid_manual_df)

# Metrics
tp = int(((hybrid_manual_df["label"] == 1) & (hybrid_manual_df["prediction"] == 1)).sum())
tn = int(((hybrid_manual_df["label"] == 0) & (hybrid_manual_df["prediction"] == 0)).sum())
fp = int(((hybrid_manual_df["label"] == 0) & (hybrid_manual_df["prediction"] == 1)).sum())
fn = int(((hybrid_manual_df["label"] == 1) & (hybrid_manual_df["prediction"] == 0)).sum())

accuracy = (tp + tn) / len(hybrid_manual_df)
precision = tp / max(tp + fp, 1)
recall = tp / max(tp + fn, 1)
f1 = 2 * precision * recall / max(precision + recall, 1e-12)
false_positive_rate = fp / max(fp + tn, 1)
false_negative_rate = fn / max(fn + tp, 1)

metrics_df = pd.DataFrame([{
    "threshold_used_for_counting": DECISION_THRESHOLD,
    "total_urls": len(hybrid_manual_df),
    "safe_urls": len(safe_urls),
    "phishing_urls": len(phishing_urls),
    "true_positives": tp,
    "true_negatives": tn,
    "false_positives": fp,
    "false_negatives": fn,
    "accuracy": accuracy,
    "precision": precision,
    "recall": recall,
    "f1": f1,
    "false_positive_rate": false_positive_rate,
    "false_negative_rate": false_negative_rate,
    "safe_mean_probability": hybrid_manual_df.loc[hybrid_manual_df["label"] == 0, "phishing_probability"].mean(),
    "phishing_mean_probability": hybrid_manual_df.loc[hybrid_manual_df["label"] == 1, "phishing_probability"].mean(),
}])

display(metrics_df)

# Chart 1: Confusion matrix
confusion = pd.DataFrame(
    [[tn, fp], [fn, tp]],
    index=["Actual safe", "Actual phishing"],
    columns=["Predicted safe", "Predicted phishing"],
)

plt.figure(figsize=(6, 5))
sns.heatmap(confusion, annot=True, fmt="d", cmap="Blues")
plt.title("Hybrid model confusion matrix")
plt.ylabel("Actual")
plt.xlabel("Predicted")
plt.show()

# Chart 2: Correct vs wrong predictions
result_counts = hybrid_manual_df["result"].value_counts().reindex(
    ["true negative", "true positive", "false positive", "false negative"],
    fill_value=0,
)

plt.figure(figsize=(8, 5))
sns.barplot(x=result_counts.index, y=result_counts.values)
plt.title("Hybrid model prediction results")
plt.ylabel("Count")
plt.xlabel("")
plt.xticks(rotation=20)
plt.show()

# Chart 3: Probability distribution
plt.figure(figsize=(9, 5))
sns.stripplot(
    data=hybrid_manual_df,
    x="expected_group",
    y="phishing_probability",
    hue="result",
    jitter=True,
    size=7,
)
plt.axhline(DECISION_THRESHOLD, color="red", linestyle="--", linewidth=1.2, label=f"counting threshold {DECISION_THRESHOLD}")
plt.ylim(0, 1)
plt.title("Hybrid model phishing probabilities")
plt.xlabel("")
plt.ylabel("Phishing probability")
plt.legend(loc="best")
plt.show()

# Chart 4: Safe vs phishing probability boxplot
plt.figure(figsize=(8, 5))
sns.boxplot(
    data=hybrid_manual_df,
    x="expected_group",
    y="phishing_probability",
)
sns.stripplot(
    data=hybrid_manual_df,
    x="expected_group",
    y="phishing_probability",
    color="black",
    alpha=0.45,
    jitter=True,
)
plt.axhline(DECISION_THRESHOLD, color="red", linestyle="--", linewidth=1.2)
plt.ylim(0, 1)
plt.title("Probability separation between safe and phishing URLs")
plt.xlabel("")
plt.ylabel("Phishing probability")
plt.show()

# Chart 5: URL-level heatmap
heatmap_df = hybrid_manual_df[["url", "expected_group", "phishing_probability", "result"]].copy()
heatmap_df["short_url"] = (
    heatmap_df["url"]
    .str.replace("https://", "", regex=False)
    .str.replace("http://", "", regex=False)
    .str.slice(0, 85)
)
heatmap_df["display_url"] = (
    np.where(heatmap_df["expected_group"] == "safe", "SAFE: ", "PHISH: ")
    + heatmap_df["short_url"]
)

heatmap_numeric = heatmap_df[["phishing_probability"]].copy()
heatmap_numeric.index = heatmap_df["display_url"]

plt.figure(figsize=(5, max(8, len(heatmap_numeric) * 0.28)))
sns.heatmap(
    heatmap_numeric.astype(float),
    annot=True,
    fmt=".3f",
    cmap="RdYlGn_r",
    vmin=0,
    vmax=1,
    linewidths=0.2,
    cbar_kws={"label": "Phishing probability"},
)
plt.title("Hybrid model URL-level phishing probabilities")
plt.xlabel("")
plt.ylabel("")
plt.show()

# Mistake tables
false_positives = hybrid_manual_df[hybrid_manual_df["result"] == "false positive"][
    ["url", "expected_group", "phishing_probability", "prediction_label"]
]

false_negatives = hybrid_manual_df[hybrid_manual_df["result"] == "false negative"][
    ["url", "expected_group", "phishing_probability", "prediction_label"]
]

print(f"False positives: {len(false_positives)}")
display(false_positives)

print(f"False negatives: {len(false_negatives)}")
display(false_negatives)